front_laser:
  topic: "/vanjee_scan716mini_front"
  filtered_topic: "/front_filtered_points"
  marker_topic: "/front_laser_filter_markers"
  filter_ranges:
    - angle_min: 180.0
      angle_max: 280.0
      range_min: 0.0
      range_max: 10.0

back_laser:
  topic: "/vanjee_scan716mini_back"
  filtered_topic: "/back_filtered_points"
  marker_topic: "/back_laser_filter_markers"
  filter_ranges:
    - angle_min: 180.0
      angle_max: 280.0
      range_min: 0.0
      range_max: 10.0
